services:
  # Site
  RAOweb:
    container_name: RAOweb
    image: ghcr.io/kakajuro/rao-web:latest
    restart: unless-stopped
    ports:
      - 4321:3000
    networks:
      - rao
      - global-network

  #Umami (website analytics)
  RAOumami:
    container_name: RAOumami
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3001:3000"
    depends_on:
      RAOumami_db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: 
      - ./umami/.env
    networks:
      - rao
      - global-network
  RAOumami_db:
    container_name: RAOumami_db
    image: postgres:15-alpine
    volumes:
      - ./umami/umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: 
      - ./umami/.env
    networks:
      - rao
      - global-network

networks:
  rao:

  global-network:
    external: true